#!/bin/sh
set -e

PATH=/sbin:/bin:/usr/sbin:/usr/bin

mkdir -p /proc
mkdir -p /sys
mount -t proc proc /proc
mount -t sysfs sysfs /sys

mkdir -p /dev
mount -t devtmpfs devtmpfs /dev

mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

# Parse kernel cmdline into vars
for p in `cat /proc/cmdline`; do
	if [ -n "$quoted" ]; then
		value="$value $p"
		if [ "`echo $p | sed -e 's/\"$//'`" != "$p" ]; then
			eval "bootparam_${quoted}=${value}"
			unset quoted
		fi
		continue
	fi

	opt=`echo $p | cut -d'=' -f1`
	opt=`echo $opt | sed -e 'y/.-/__/'`
	if [ "`echo $p | cut -d'=' -f1`" = "$p" ]; then
		eval "bootparam_${opt}=true"
	else
		value="`echo $p | cut -d'=' -f2-`"
		if [ "`echo $value | sed -e 's/^\"//'`" != "$value" ]; then
			quoted=${opt}
			continue
		fi
		eval "bootparam_${opt}=\"${value}\""
	fi
done

ifconfig lo up 127.0.0.1
ifconfig eth0 up
udhcpc -i eth0

modprobe tdx-guest || true

exec /bin/sh
