#!/bin/sh
set -e

export PATH=/sbin:/bin:/usr/sbin:/usr/bin

mkdir -p /proc
mkdir -p /sys
mkdir -p /run
mkdir -p /tapp
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t tmpfs tmpfs /run
mount -t tmpfs tmpfs /tapp

mkdir -p /dev
mount -t devtmpfs devtmpfs /dev

mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

ifconfig lo up 127.0.0.1
ifconfig eth0 up
udhcpc -i eth0

modprobe tdx-guest || true

source /scripts/boot-vars
source /scripts/kmfs-setup

# mount move dirs
mount_move_all() {
    for dir in $@; do
        mkdir -p /root/$dir
        mount --move /$dir /root/$dir
    done
}
mount_move_all sys proc dev run tapp

echo "Switching to new root"
exec switch_root /root /init
