#!/bin/bash
if [ -n "$BASH_SOURCE" ]; then
    THIS_SCRIPT=$BASH_SOURCE
elif [ -n "$ZSH_NAME" ]; then
    THIS_SCRIPT=$0
else
    THIS_SCRIPT="$(pwd)/dev-setup"
    if [ ! -e "$THIS_SCRIPT" ]; then
        echo "Error: $THIS_SCRIPT doesn't exist!" >&2
        echo "Please run this script in dev-setup's directory." >&2
        exit 1
    fi
fi
THIS_SCRIPT=$(realpath "$THIS_SCRIPT")
THIS_DIR=$(dirname "$THIS_SCRIPT")

pushd .
source $THIS_DIR/poky/oe-init-build-env $THIS_DIR/bb-build

bitbake-layers add-layer \
    $THIS_DIR/meta-confidential-compute \
    $THIS_DIR/meta-openembedded/meta-oe \
    $THIS_DIR/meta-openembedded/meta-python \
    $THIS_DIR/meta-openembedded/meta-networking \
    $THIS_DIR/meta-openembedded/meta-filesystems \
    $THIS_DIR/meta-virtualization \
    $THIS_DIR/meta-rust-bin \
    $THIS_DIR/meta-dstack \

popd

# Add scripts/bin to PATH if not already present
if [[ ":$PATH:" != *":$THIS_DIR/scripts/bin:"* ]]; then
    export PATH=$PATH:$THIS_DIR/scripts/bin
fi
