#!/bin/bash
shopt -s nullglob

if [ -n "$BASH_SOURCE" ]; then
    THIS_SCRIPT=$BASH_SOURCE
elif [ -n "$ZSH_NAME" ]; then
    THIS_SCRIPT=$0
else
    THIS_SCRIPT="$(pwd)/dev-setup"
    if [ ! -e "$THIS_SCRIPT" ]; then
        echo "Error: $THIS_SCRIPT doesn't exist!" >&2
        echo "Please run this script in dev-setup's directory." >&2
        exit 1
    fi
fi
THIS_SCRIPT=$(realpath "$THIS_SCRIPT")
THIS_DIR=$(dirname "$THIS_SCRIPT")

LAYERS="$THIS_DIR/meta-confidential-compute \
    $THIS_DIR/meta-openembedded/meta-oe \
    $THIS_DIR/meta-openembedded/meta-python \
    $THIS_DIR/meta-openembedded/meta-networking \
    $THIS_DIR/meta-openembedded/meta-filesystems \
    $THIS_DIR/meta-virtualization \
    $THIS_DIR/meta-rust-bin \
    $THIS_DIR/meta-dstack"

if [ -z "$1" ]; then
    BUILD_DIR=$THIS_DIR/bb-build
else
    BUILD_DIR=$(realpath "$1")
fi
if [ ! -f "$BUILD_DIR/conf/local.conf" ]; then
    mkdir -p "$BUILD_DIR/conf"
    cp -f "$THIS_DIR/bb-build/conf/local.conf" "$BUILD_DIR/conf/local.conf"
fi

OE_INIT=$THIS_DIR/poky/oe-init-build-env

for script in $THIS_DIR/setup.d/*.sh; do
    source "$script"
done

pushd .
source $OE_INIT $BUILD_DIR
popd

bitbake-layers add-layer $LAYERS

# Add scripts/bin to PATH if not already present
if [[ ":$PATH:" != *":$THIS_DIR/scripts/bin:"* ]]; then
    export PATH=$PATH:$THIS_DIR/scripts/bin
fi
