FROM ubuntu:24.04@sha256:3afff29dffbc200d202546dc6c4f614edc3b109691e7ab4aa23d02b42ba86790

# Prevent timezone prompt by setting noninteractive frontend and configuring tzdata
ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Etc/UTC \
    TZDATA=Etc/UTC \
    LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8

# Set timezone
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Install required packages
RUN apt update && apt install -y \
    build-essential \
    chrpath \
    diffstat \
    lz4 \
    wireguard-tools \
    python3 \
    locales \
    git \
    file \
    gawk \
    wget \
    libclang-dev \
    xorriso \
    cpio \
    zstd

# Generate locale for bitbake
RUN locale-gen en_US.UTF-8
